### PR TITLE
Form Contract for all inputs

### PR DESCRIPTION
**Pull request by tobich**
Tests behavior of all input components inside native HTML `<form />`.
Performs end-to-end test (submits the form and checks the actual URL parameters).

@tyv : TimePicker is included but skipped. The component includes some extra named inputs which sneak into the final URL. I couldn't fix it easily, so I am leaving this for a future separate PR.

### CODE REVIEW

**Review by tyv — APPROVED** [review]

**Comment by tyv** [comment]
@wtfil take a look and after it merged make test for Timepicker works

**Comment by tobich** [comment]
Pull requested euthanized after @nadavov decision

**Comment by tyv** [comment]
any reasons would be publicly written?

**Comment by wtfil** [comment]
fixed #47ef7532e5740d050e968234856674f640b6e301

**Pull request closed without merging**
