### PR TITLE
Abumami/slider readme updates and editing

### PR DESCRIPTION
**Pull request by abumami**
- edited readme
- made changes according to overview issue #354 

@maksymc Please check the onChange signature as we discussed.

### CODE REVIEW

**Comment by abumami** [comment]
@maksymc I need more information on the issue "progressMarks and marks can be implemented using a background image in repeat according to step value".

**Comment by maksymc** [comment]
@abumami it says that progress marks "CAN" be implemented using BG. I am not sure that they should. 
I'll review comments from Nadav & take necessary actions. You can leave it as it is right now.

**Comment by abumami** [comment]
OK - thanks Max.

**Comment by maksymc** [comment]
@abumami, I've added few changes to the PR. 
Sorry for the mess, next time will do it in a cleaner way;)

**Pull request merged**
